services:
  kafka:
    image: apache/kafka:4.0.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
#      # Configure listeners for both docker and host communication
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      # Settings required for KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
#      # Required for a single node cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - clinicafiap-net

  controle-servicos:
    platform: linux/amd64
    build: ./clinicafiap-controle-servicos
    container_name: controle-servicos
    ports:
      - "8761:8761"
    networks:
      - clinicafiap-net

  gateway:
    platform: linux/amd64
    build: ./clinicafiap-gateway
    container_name: gateway
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://controle-servicos:8761/eureka
    depends_on:
      - controle-servicos
    networks:
      - clinicafiap-net

  usuarios-service:
    platform: linux/amd64
    build: ./clinicafiap-usuarios
    container_name: usuarios-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://controle-servicos:8761/eureka
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "9090:9090"
    depends_on:
      - controle-servicos
    networks:
      - clinicafiap-net

  consultas-service:
    platform: linux/amd64
    build: ./clinicafiap-consultas
    container_name: consultas-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://controle-servicos:8761/eureka
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - controle-servicos
      - usuarios-service
      - kafka
    networks:
      - clinicafiap-net

  notificacoes-service:
    platform: linux/amd64
    build: ./clinica-fiap-notificacao-consumer
    container_name: notificacoes-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://controle-servicos:8761/eureka
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - controle-servicos
      - consultas-service
      - kafka
    networks:
      - clinicafiap-net

networks:
  clinicafiap-net:
    driver: bridge