services:
  controle-servicos:
    build: ./clinicafiap-controle-servicos
    container_name: controle-servicos
    ports:
      - "8761:8761"
    networks:
      - clinicafiap-net

  gateway:
    build: ./clinicafiap-gateway
    container_name: gateway
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://controle-servicos:8761/eureka
    depends_on:
      - controle-servicos
    networks:
      - clinicafiap-net

  usuarios-service:
    build: ./clinicafiap-usuarios
    container_name: usuarios-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://controle-servicos:8761/eureka
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - controle-servicos
    networks:
      - clinicafiap-net

  consultas-service:
    build: ./clinicafiap-consultas
    container_name: consultas-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://controle-servicos:8761/eureka
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - controle-servicos
      - usuarios-service
    networks:
      - clinicafiap-net

  # notificacoes-service:
  #   build: ./clinica-fiap-notificacao-consumer
  #   container_name: notificacoes-service
  #   ports:
  #     - "8082:8082"
  #   environment:
  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://controle-servicos:8761/eureka
  #     - SPRING_PROFILES_ACTIVE=docker
  #     - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
  #   depends_on:
  #     - controle-servicos
  #     - consultas-service
  #     - kafka
  #   networks:
  #     - clinicafiap-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - clinicafiap-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - clinicafiap-net

networks:
  clinicafiap-net:
    driver: bridge